from pathlib import Path
import hashlib,json,subprocess,datetime,re
root=Path.cwd();out=root/'assets/review/commonware-reuse-20261004/wave15/body-final';baseline='1212e680e8e8f1316b9557a16b2e5b5acfe1ea8a';sha=lambda b:hashlib.sha256(b).hexdigest();assert subprocess.check_output(['git','rev-parse','HEAD']).decode().strip()==baseline
previous=root/'assets/review/commonware-reuse-20261004/wave14/body-requirements/REQUIREMENTS_RECEIPT.json';prior=json.loads(previous.read_text());record={'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline':baseline,'docs':[],'goal_complete':False,'scope':'Final documentation readiness/source fit, not compiled protocol, no fresh remote request or raw attachment-byte proof','saved_prior_evidence':{'path':str(previous.relative_to(root)),'sha256':sha(previous.read_bytes()),'saved_page_readback_scope':'38 saved wave13 readbacks independently semantically rechecked in wave14; reader bytes unchanged now'}}
for p in subprocess.check_output(['git','ls-files','docs']).decode().splitlines():
 b=(root/p).read_bytes();assert b==subprocess.check_output(['git','show',baseline+':'+p]);assert b==subprocess.check_output(['git','show','8c75c0486e1adb6e81dda9f50558fa75d2a5510b:'+p]);assert b==(Path('/Users/leojin/dev/baton')/p).read_bytes();record['docs'].append({'path':p,'sha256':sha(b),'baseline_equal':True,'prior_published_reader_equal':True,'mirror_equal':True})
record['diagrams']=prior['diagrams'];
for e in record['diagrams']:assert sha((root/e['source']).read_bytes())==e['source_sha256'];assert sha((root/Path(e['source']).with_suffix('.svg')).read_bytes())==e['svg_sha256']
md=(root/'docs/overview/rust-interfaces.md').read_text();parts=re.findall(r'```rust\n([\s\S]*?)\n```',md);export='// @generated from docs/overview/rust-interfaces.md; edit that Markdown source.\n// Application interface proposals only; no protocol implementation.\n\nuse std::future::Future;\n\n'+'\n\n'.join(re.sub(r'^use std::future::Future;\n\n','',p) for p in parts)+'\n';assert export.encode()==(root/'docs/assets/interfaces/baton.rs').read_bytes();record['traits']=re.findall(r'^pub trait (\w+)',md,re.M);record['methods']=re.findall(r'\bfn (\w+)\(', '\n'.join(parts));assert len(record['traits'])==5 and len(record['methods'])==30;record['export_exact']=True;record['blank_choices']=prior['blank_choices'];assert record['blank_choices']==39
record['retained_sources']=[]
for e in prior['retained_sources']:
 local=e.get('local',e['path']);b=(root/local).read_bytes();assert sha(b)==e['sha256'];blob=hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest();assert blob==e['git_blob'];record['retained_sources'].append({'local':local,'sha256':sha(b),'git_blob':blob,'scope':'Previously pinned/tree-checked primary bytes rehashed/reread selectively, no fresh retrieval'})
engine=root/'assets/review/commonware-reuse-20261004/wave11/body-coverage/sources/native/consensus/src/multimmit/engine.rs';b=engine.read_bytes();blob=hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest();treepath=root/'assets/review/commonware-reuse-20261004/wave11/body-coverage/trees/native.json';tree=json.loads(treepath.read_text());assert not tree['truncated'];assert {e['path']:e['sha'] for e in tree['tree']}['consensus/src/multimmit/engine.rs']==blob;record['retained_sources'].append({'local':str(engine.relative_to(root)),'sha256':sha(b),'git_blob':blob,'tree':str(treepath.relative_to(root)),'tree_sha256':sha(treepath.read_bytes()),'scope':'Retained native Engine callback bounds/new construction reread and blob rechecked, no fresh retrieval'})
runpath=root/'assets/review/commonware-reuse-20261004/run.json';run=json.loads(runpath.read_text());record['objective']={k:run[k] for k in ['objective','started_at_utc','review_window_end_utc','status','requirements']};record['prior_ledger']=[]
for wave in run['waves']:
 for e in wave.get('reports',[]):
  p=root/'assets/review/commonware-reuse-20261004'/e['path'];assert sha(p.read_bytes())==e['sha256'];record['prior_ledger'].append({'wave':wave['wave'],**e})
record['authority']=[]
for p in ['AGENTS.md','README.md','BATON_HANDOFF.md','assets/review/commonware-reuse-20261004/run.json']:
 record['authority'].append({'path':p,'sha256':sha((root/p).read_bytes())})
record['wave_progression']=[{'wave':w['wave'],'status':w['status'],'reports':len(w.get('reports',[]))} for w in run['waves']];record['original_interface_baseline']='38f64555e27fb88feb2a1f4be6ae2c133c6082e7';record['original_rust_sha256']=sha(subprocess.check_output(['git','show',record['original_interface_baseline']+':docs/overview/rust-interfaces.md']))
(out/'COMPLETION_EVIDENCE_RECEIPT.json').write_text(json.dumps(record,indent=2)+'\n');print(json.dumps({'docs':len(record['docs']),'diagrams':len(record['diagrams']),'traits':len(record['traits']),'methods':len(record['methods']),'source_receipt_entries':len(record['retained_sources']),'prior_reports':len(record['prior_ledger']),'receipt_sha256':sha((out/'COMPLETION_EVIDENCE_RECEIPT.json').read_bytes())},indent=2))
