from pathlib import Path
import urllib.request,hashlib,json,concurrent.futures,datetime
base=Path(__file__).parent;pins={'native':('commonwarexyz/monorepo','534af0ede48affd35b2111522527547b4cc9bf72'),'alto':('commonwarexyz/alto','1d87569348b5560699465a72d691d90f18affb9c'),'tempo':('tempoxyz/tempo','61c979a524f9af5de9c540a0088c429a44741e4c')};paths={'native':['consensus/src/multimmit/'+p for p in ['mod.rs','engine.rs','storage/mod.rs','storage/journal.rs','storage/checkpoint.rs','actors/voter/journal.rs','actors/voter/actor.rs','actors/voter/executor.rs','actors/resolver/mod.rs','actors/resolver/actor.rs','machine/mod.rs','machine/durability.rs','machine/reducer.rs','machine/state.rs','machine/admission.rs','machine/emission.rs','machine/finality.rs','machine/algebra/tips.rs','machine/controller.rs','types/activity.rs','types/history.rs','types/tally.rs','types/certificate.rs','types/block.rs','scheme/mod.rs']]+['consensus/src/marshal/core/actor.rs','consensus/src/marshal/resolver/handler.rs','consensus/src/marshal/store.rs','storage/src/archive/mod.rs','storage/src/journal/contiguous/mod.rs','storage/src/metadata/storage.rs'],'alto':['chain/src/engine.rs','follower/src/archive.rs'],'tempo':['crates/consensus/src/alias.rs','crates/consensus/src/storage/hybrid/mod.rs']}
def get(u):
 with urllib.request.urlopen(urllib.request.Request(u,headers={'User-Agent':'Baton-native-evidence-audit'}),timeout=90) as r:return r.read()
def tree(tag):
 repo,pin=pins[tag];b=get(f'https://api.github.com/repos/{repo}/git/trees/{pin}?recursive=1');t=json.loads(b);assert not t.get('truncated');(base/f'{tag}-tree.json').write_bytes(b);return tag,{x['path']:x['sha'] for x in t['tree'] if x['type']=='blob'}
with concurrent.futures.ThreadPoolExecutor(max_workers=3) as ex:trees=dict(ex.map(tree,pins))
def fetch(j):
 tag,path=j;repo,pin=pins[tag];u=f'https://raw.githubusercontent.com/{repo}/{pin}/{path}';b=get(u);f=base/'sources'/tag/path;f.parent.mkdir(parents=True,exist_ok=True);f.write_bytes(b);blob=hashlib.sha1(f'blob {len(b)}\0'.encode()+b).hexdigest();assert blob==trees[tag][path];return {'source':tag,'repo':repo,'pin':pin,'path':path,'url':u,'local':str(f),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest(),'git_blob':blob,'tree_blob':trees[tag][path],'git_blob_verified':True}
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as ex:rows=list(ex.map(fetch,[(tag,p) for tag,ps in paths.items() for p in ps]))
(base/'source-manifest.json').write_text(json.dumps({'fetched_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'pins':pins,'sources':rows},indent=2)+'\n');print('fresh files',len(rows),'all blobs match fresh pinned trees')
