from pathlib import Path
import json,hashlib,urllib.request,concurrent.futures,datetime
b=Path(__file__).parent;pins={'native':'534af0ede48affd35b2111522527547b4cc9bf72','release':'d476a2361ce6840d2b9d0aa6fb30a924429046d4'}
paths={'native':['consensus/src/lib.rs','consensus/src/multimmit/mod.rs','consensus/src/multimmit/engine.rs','consensus/src/multimmit/tests.rs','consensus/src/multimmit/mocks/mod.rs','consensus/src/multimmit/mocks/cluster.rs','consensus/src/multimmit/mocks/attached.rs','consensus/src/multimmit/test_utils/mod.rs','consensus/src/multimmit/machine/mod.rs','consensus/src/multimmit/machine/tests/mod.rs','consensus/src/multimmit/machine/tests/test_utils.rs','consensus/src/multimmit/machine/tests/test_utils/world.rs','consensus/src/multimmit/machine/tests/world.rs','consensus/Cargo.toml','examples/log-multimmit/src/main.rs','examples/log-multimmit/src/application/actor.rs','examples/log-multimmit/src/application/mod.rs','runtime/src/deterministic.rs','runtime/src/lib.rs','p2p/src/simulated/mod.rs','p2p/src/simulated/ingress.rs','p2p/src/simulated/network.rs','p2p/src/lib.rs'],'release':['runtime/src/deterministic.rs','p2p/src/simulated/mod.rs','p2p/src/simulated/ingress.rs']};trees={}
for tag in pins:
 t=json.loads((b/(tag+'-tree.json')).read_text());assert not t.get('truncated');trees[tag]={x['path']:x['sha'] for x in t['tree'] if x['type']=='blob'}
def fetch(x):
 tag,p=x;pin=pins[tag];u=f'https://raw.githubusercontent.com/commonwarexyz/monorepo/{pin}/{p}';v=urllib.request.urlopen(u,timeout=45).read();f=b/'sources'/tag/p;f.parent.mkdir(parents=True,exist_ok=True);f.write_bytes(v);blob=hashlib.sha1(f'blob {len(v)}\0'.encode()+v).hexdigest();assert blob==trees[tag][p];return {'source':tag,'repo':'commonwarexyz/monorepo','pin':pin,'path':p,'url':u,'local':str(f.resolve()),'sha256':hashlib.sha256(v).hexdigest(),'git_blob':blob,'tree_blob':trees[tag][p],'bytes':len(v)}
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as e:rows=list(e.map(fetch,[(tag,p) for tag,ps in paths.items() for p in ps]))
(b/'source-manifest.json').write_text(json.dumps({'fresh_fetched_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'pins':pins,'complete_trees':2,'sources':rows},indent=2)+'\n');print(len(rows),'fresh blob matched files')
