from pathlib import Path
import hashlib,json,datetime,re
b=Path(__file__).parent;root=b.parents[4];r=json.loads((b/'global-review/receipt.json').read_text());pages=r['page_hashes'];base=r['baseline']
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
assert set(r['changed_docs'])==set(pages);assert pages['docs/reference/verification.md']=='fcb5f87d3fe5b6ed98259b406004f54c26619d9974fde95c4c14df658062231b'
for p,h in pages.items():assert digest(root/p)==h,p+' changed during review'
for x in r['fresh_matched_source_files_for_new_citations']:
 v=Path(x['local']).read_bytes();assert digest(Path(x['local']))==x['sha256'];assert hashlib.sha1(f'blob {len(v)}\0'.encode()+v).hexdigest()==x['tree_blob']
s=(root/'docs/reference/verification.md').read_text();assert s.count('| Not run |')==9
text=f'''# Wave 9 final global reader and preservation review

Reviewer `/root/reuse_orderer_v3`; baseline `{base}`. **Pass: no remaining actionable correction or publication blocker in the final one-page diff.** The review is bound to `docs/reference/verification.md` SHA-256 `{pages['docs/reference/verification.md']}`. This verifies source fit and reader/preservation constraints, not compiled integration, executed tests, protocol proof, publication or completion of the six-hour goal.

Exactly this one tracked docs page differs from baseline, with 14 inserted lines. All original case/status rows and closing application requirements remain unchanged. Reviewer made no canonical edits.

## Exact source and reader fit

All 14 introduced citation occurrences resolve against nine independently fresh raw source files, Git-blob matched to complete newly authenticated native/Tempo/Alto trees from this reviewer's current wave. The same full raw sources were independently retrieved and checked for the three peer reports; public path/gates and current line text were verified, rather than assuming every nested pub declaration is reachable. New anchors point to actual simulated registration (ingress428), actual native Engine::new635 and actual Blob::start_sync633. Detailed source identities/anchors/page hashes are in global-review/receipt.json.

- Public simulated Network/Oracle/Control reuse correctly provides existing Sender/Receiver handles, two-argument channel registration, directed topology controls and separate native/body/result channel assembly. This is the same native actor interface boundary, not proof of encrypted deployment handshake or discovery. No transport/simulator/peer-provider/ACK framework is introduced.
- Native feature/non-wasm availability and exact path `multimmit::mocks::cluster::Cluster` match the exports; mocks/mod.rs exports cluster without reexporting Cluster. The fixed MockApplication/NoopReporter and no-op full-body Relay are explicit. Cluster::launch_with replaces transport/signing slot, not generic application callbacks. Public Engine::new instead permits the existing Automaton/Relay/Reporter attachment. No private Core/extraction/recording test helper is claimed as externally callable.
- Cluster per-engine abort/restart operates within a live enclosing runtime/network. Public Runner::start_and_recover/From<Checkpoint> are the whole runtime boundary; cleanup destroys tasks/root, and a panic resumes without returning Checkpoint. Reopening services and writer authority remains required. A runtime checkpoint is not an execution checkpoint, application durable receipt, filesystem image or preservation of arbitrary external tasks.
- Sync wording is deliberately scoped to Blob::start_sync. Default PendingSyncs parks the completion future before the inner sync, while native completion_delayed starts the inner sync first and parks completion observation. Default does not gate every ordinary sync or synchronous write; separately armed gate controls that path. Actual inner progress/durability must be observed independently. Lost application ACK occurs after complete durable receipt and is not identical to a blocked blob flush. The constructor is absent from inspected registry-release mocks and no release/native type compatibility is inferred.
- Tempo actual workspace E2E assembly really wires simulated consensus channels into its body/Marshal/Simplex and separate execution runtime; Alto's private full-chain two-run test really reopens runtime storage and re-registers validators without relinking peers, then checks recovered uploads and queue drain metrics. Their graph/workload/private fixture/certificate types are source references, not ready native Baton imports or adopted n/quorum choices.
- Comparing public Auditor::state fingerprints checks repeatability of the audited runtime trace; returning one fingerprint alone would not. The final reader explicitly separates exact order, custody, full f+1 result eligibility and linked application state assertions, and says external VM/thread/I/O does not automatically inherit deterministic scheduling. No throughput/safety/native-prefix/dense-delivery/application recovery claim is made.

Independent NETWORK_STORAGE_ROOT_CROSS_REVIEW binds the three reports: simulated-network11af5383..., storage-fixturesca96c737..., fixture-boundaries241415f6... after its Alto constructor-anchor correction. The cross-review independently fetched 40 primary files/five complete trees and checked 78 report anchors. This global review additionally binds the final adopted prose and exact page bytes. The exact fixture path correction was applied by root; this reviewer corrected only its own assigned report/delta, without canonical changes.

## Preservation and global constraints

Read-only comparison of all tracked docs against baseline passes:

- All 32 Markdown files preserve exact ordered headings, explicit compatibility anchors and every old external source URL occurrence/multiplicity. All Rust and Mermaid fenced blocks are byte-identical; all 56 tracked non-Markdown docs assets match baseline, including rendered diagrams and Rust export.
- Five application traits remain TxPool, Orderer, Baton, Executor and Storage with 30 methods. No public Runtime/Planner/reschedule/body/query/result/test trait, fixture actor, framework or production module is added.
- All 39 policy cells remain blank. Existing routing-versus-packing alternative, pool/workload/backend/native-port scope, body/root/codec/budget/retention choices, result boundaries and execution/work scheduling/cancellation choices remain unselected. The new table names actual reusable mechanisms and retains application responsibility.
- All nine original verification statuses remain exactly Not run; no test, fuzz target, benchmark, compile or implementation was executed by this review. Native source pin and existing release/chain graph distinctions remain unchanged.
- Existing native n=5f+1/tips/extensions, fixed report snapshot/deadline, completed bounded candidate search and exact selected-prefix/proposal protection constraints remain unchanged. Cut continues without report/timer/optimizer/direction/peer/observer ACK prerequisites. Existing adoption/continuation/view-recovery proof obligations remain open.
- Orderer dense delivery continues to stop unresolved slots, emit authenticated included slots and skip only irrevocably-empty slots under immutable authenticated interpretation. Sparse native finality/Inspection/fixed mock verification cannot substitute for exact source witnesses, policy interpretation or durable external delivery.
- Executor owns parent-linked execution/path/tree/result certification/normal-path sync; Storage owns selected root/material/canonical apply/durability/physical retention. Root calculation remains deferred until useful; no full Stateful Application/actor dependency or automatic unsealed fork is introduced.
- f+1 eligible distinct valid signatures must match full exact input/base/runtime/result. DirectExecuted and ImportedVerified remain distinct. Certificate and applicable material must be verified before stopping unfinished execution; actual worker/access quiescence and one canonical writer/fence/recovery linkage remain requirements.
- Orderer→Executor exact input, Storage durable state/output/cursor/provenance, verified CommitResult→Orderer ACK and outcomes→TxPool remain mandatory application predicates. Optional Baton observation does not gate result certification, sync, canonical apply or ACK. The fixture helpers do not enforce these predicates themselves.

Read-only documentation check passes: 31 content pages, 257 local links, 18 rendered diagrams, 39 blank choices, zero failures. This checks docs navigation/export/asset consistency only, not protocol behavior.

## Remaining risks and limits

Selected native application adapters and dependency graph remain uncompiled. The test plan still requires actual bounded body/custody, authenticated exact-source/dense-order/native-prefix, canonical outcome/restart, rootless branch, verified material/certificate/provenance and single-writer multi-store recovery integration. Deterministic memory/fault/gate simulation is not exhaustive device-crash coverage, and external execution may need explicitly controlled boundaries. Any changed page hash requires checking the changed revision; publication/remote readback and six-hour completion are separate root-owned work.
'''
(b/'DOCS_GLOBAL_REVIEW.md').write_text(text)
c={'reviewer':'/root/reuse_orderer_v3','checked_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline':base,'result':'pass_no_remaining_actionable_corrections','page_hashes':pages,'markdown_pages_preserved':32,'non_md_docs_assets_unchanged':56,'traits':r['public_traits'],'methods':r['method_count'],'blank_choices':39,'verification_status_rows_unrun':9,'new_citation_occurrences':14,'fresh_blob_matched_sources_for_new_citations':9,'additional_raw_fetches':0,'docs_check':r['docs_check'],'detailed_receipt_sha256':digest(b/'global-review/receipt.json'),'report_sha256':digest(b/'DOCS_GLOBAL_REVIEW.md'),'canonical_edits':False,'implementation_compile_tests':False,'publication_or_six_hour_completion_claim':False}
(b/'DOCS_GLOBAL_REVIEW_RECEIPT.json').write_text(json.dumps(c,indent=2)+'\n');print(json.dumps({'report':c['report_sha256'],'compact_receipt':digest(b/'DOCS_GLOBAL_REVIEW_RECEIPT.json'),'detailed_receipt':c['detailed_receipt_sha256'],'pages':pages},indent=2))
