from pathlib import Path
import json,subprocess,urllib.request,hashlib,concurrent.futures,datetime
b=Path(__file__).parent;pins={'nunchi':('nunchi-labs/sdk','eea35ced709f68c15d6fbc8bcc754696a7e44374'),'constantinople':('commonwarexyz/constantinople','3b6c92e76bf582855615844a4175b8304808f6a9'),'tempo':('tempoxyz/tempo','61c979a524f9af5de9c540a0088c429a44741e4c'),'reth':('paradigmxyz/reth','038edab20dfff017f7a7502e683c732e5628ad89'),'native':('commonwarexyz/monorepo','534af0ede48affd35b2111522527547b4cc9bf72')};paths={'nunchi':['Cargo.toml','mempool/Cargo.toml','mempool/src/lib.rs','mempool/src/tx.rs','mempool/src/pool.rs','mempool/src/actor.rs','mempool/src/config.rs','mempool/src/status.rs','chain/src/application.rs','chain/src/execution.rs','common/src/transaction.rs'],'constantinople':['Cargo.toml','crates/mempool/src/lib.rs','crates/mempool/src/webserver/mailbox.rs','crates/mempool/src/webserver/actor.rs','crates/application/src/consensus/glue.rs','crates/application/src/consensus/lifecycle.rs','crates/primitives/src/transaction.rs'],'tempo':['Cargo.lock','crates/transaction-pool/src/tempo_pool.rs','crates/transaction-pool/src/maintain.rs','crates/payload/builder/src/lib.rs','crates/node/src/node.rs'],'reth':['crates/transaction-pool/src/traits.rs','crates/transaction-pool/src/pool/mod.rs','crates/transaction-pool/src/maintain.rs','crates/transaction-pool/src/lib.rs'],'native':['Cargo.toml','consensus/src/lib.rs','consensus/src/multimmit/actors/voter/executor.rs']}
def tree(tag):
 r,p=pins[tag];v=subprocess.check_output(['gh','api',f'repos/{r}/git/trees/{p}?recursive=1']);t=json.loads(v);assert not t.get('truncated');(b/(tag+'-tree.json')).write_bytes(v);return tag,{x['path']:x['sha'] for x in t['tree'] if x['type']=='blob'}
with concurrent.futures.ThreadPoolExecutor(max_workers=5) as e:trees=dict(e.map(tree,pins))
def fetch(x):
 tag,path=x;r,p=pins[tag];u=f'https://raw.githubusercontent.com/{r}/{p}/{path}';v=urllib.request.urlopen(u,timeout=60).read();f=b/'sources'/tag/path;f.parent.mkdir(parents=True,exist_ok=True);f.write_bytes(v);blob=hashlib.sha1(f'blob {len(v)}\0'.encode()+v).hexdigest();assert blob==trees[tag][path];return {'source':tag,'repo':r,'pin':p,'path':path,'url':u,'local':str(f.resolve()),'sha256':hashlib.sha256(v).hexdigest(),'git_blob':blob,'tree_blob':trees[tag][path],'bytes':len(v),'blob_verified':True}
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as e:rows=list(e.map(fetch,[(tag,p) for tag,ps in paths.items() for p in ps]));(b/'source-manifest.json').write_text(json.dumps({'fresh_fetched_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'pins':pins,'sources':rows},indent=2)+'\n');print(len(rows),'fresh files/5complete authenticated trees; all blobs match')
