from pathlib import Path
import json,hashlib,datetime
b=Path(__file__).parent;w=b.parent;d=b/'independent-cross-review';m=json.loads((d/'source-manifest.json').read_text())
for name in ['body-codec','execution-tree']:
 assert hashlib.sha256((w/name/'REPORT.md').read_bytes()).hexdigest()==m['report_hashes'][name]
 assert hashlib.sha256((w/name/'READER_DELTA.md').read_bytes()).hexdigest()==m['reader_delta_hashes'][name]
counts={name:len(set((x['repo'],x['pin'],x['path']) for x in m['anchors'] if x['report']==name)) for name in ['body-codec','execution-tree']}
body=f'''# Independent body-codec cross-review

Reviewer `/root/reuse_orderer_v3`. Reviewed report SHA `{m['report_hashes']['body-codec']}` and reader delta SHA `{m['reader_delta_hashes']['body-codec']}`. Report unchanged when this review closed. Result: **no actionable correction required**.

Fresh independent retrieval: {counts['body-codec']} cited primary source files within the combined 34-file cross-review manifest, four newly authenticated complete/non-truncated pinned Git trees, all SHA-256/Git blob identities matching. Each cited source anchor resolves within independently retrieved bytes. The producer report's receipts were not accepted as fresh verification. `independent-cross-review/source-manifest.json` records sources, anchors and exact report identities. No new MCP tool was called by this reviewer; indexed release corroboration is the report author's explicitly labeled evidence, not a claimed fresh native assembly.

Verified decisive claims:

- Native `Read::Cfg` is Clone+Send+Sync+'static. Write+EncodeSize provides blanket Encode; Read provides Decode; Codec and CodecShared are blanket combinations, with CodecShared adding Send+Sync. `decode_cfg` rejects trailing bytes. Nested `read_cfg` intentionally does not impose whole-frame consumption. Actual encode_size mismatch asserts; neither interface is schema/domain validation.
- Vec uses `(RangeCfg<usize>, T::Cfg)` and Bytes uses RangeCfg. usize container prefixes encode checked u32 varints; the native decoder rejects overflow/nonminimal terminal-zero encodings. Default element decoding's initial allocation cap does not bound all loop/element work; the report retains separate count, inner and complete byte limits with no numbers chosen.
- Buffered Engine accepts `M: Digestible + Codec` and configuration `M::Cfg`; concrete immutable Archive takes `V: CodecShared` and `V::Cfg`. Digestible supplies Clone/Send/Sync but does not compute a hash itself. Generic resolver's outer unit key/Bytes codec does not force unit body configuration.
- Native Engine's actual A/R bounds are Automaton with native Context/H::Digest and Relay with Plan=(); there is no full-body Block/CertifiableBlock/Application bound. Header codec/hash already covers epoch, producer chain, height, parent header digest and commitment; body commitment and header identity remain separate.
- Tempo's digest is EL block header hash; it is **not** the hash of complete Commonware wire bytes. Its constructor verifies execution body/header and BAL relationship, and Read invokes the validated path. Alto derives digest from selected fields independently of its wire prefixes; bounded Read config is non-unit. Neither source mandates wire-byte hashing or an adopted Baton hash/schema. Tempo's body type remains crate-private. Report uses these as patterns, not imports or a custody proof.
- Exact content/digest coherence, authenticated native header-to-body join, retained parent custody and pending-versus-permanent-invalid callback behavior remain application attachment obligations. Codec success alone establishes neither custody nor authenticated parent relation. No new public body trait, generic parent lookup/cache/serializer, schema or numerical limit is proposed.

The small root draft addition to `docs/consensus/block-body.md` codec table/prose is consistent with these checks: it retains open format/hash/domain/limits, no Simplex type requirement, configurable body bounds, and parent custody. The separate newly added Reporter paragraph belongs to the notification reviewer and is outside this report's independent scope.

Remaining limits: source evidence only. No compilation/native test/runtime custody trace, chosen commitment schema, complete decoder-work bound or native integration proof. No full-body ACK/custody quorum/default is adopted; native cut/report/direction no-wait remains intact.
'''
tree=f'''# Independent execution-tree cross-review

Reviewer `/root/reuse_orderer_v3`. Reviewed report SHA `{m['report_hashes']['execution-tree']}` and reader delta SHA `{m['reader_delta_hashes']['execution-tree']}`. Report unchanged when review closed. Result: **no actionable correction required**.

Fresh independent retrieval: {counts['execution-tree']} cited primary files within the combined 34-file manifest, four newly authenticated complete/non-truncated pinned trees; all raw Git blobs match. Independently retrieved bytes support every cited anchor. No earlier receipt was treated as fresh proof. See `independent-cross-review/source-manifest.json` for exact file/anchor hashes. The author's explicit MCP v2026.9.0 evidence remains release corroboration; this review establishes the decisive actual native behavior from fresh pinned source, without invoking MCP or inferring package identity compatibility.

Verified precise ownership/API boundary:

- Native `batch_chain` is public and exports Commitment/AncestorBounds/Bounds, with public fields. Commitment equality includes both operation size and root. Live ancestor walkers, collection/adjustment and Bounds validation remain pub(crate); no public BatchChain actor/owner was found in this surface. Public projections represent storage applicability, not block identity, runtime, executed order, provenance or membership/certificate verification.
- Any and Current public `to_batch` wrap already-computed committed state. Any builds empty local diff and log anchor with no parent; Current keeps the existing canonical root and grafted/bitmap snapshot. This supplies a sealed anchor without sealing every newly abandoned execution attempt. It does not make a persistent snapshot safe across divergent commits or expose a rootless multi-child fork.
- Any unsealed Base::Child retains immediate parent Arc; the sealed parent's object link is Weak. into_parts privately collects strong live ancestors before Merkle work. Lower Merkle batches retain Arc refs to ancestor **data** for apply while Weak links serve further lookup/walk. Those data refs do not preserve all original objects needed for new child reads/merkleization. Dropping still-needed unapplied ancestor objects can invalidate use; lower source warns invalid methods may return wrong data without error. Keeping only the leaf is not a general liveness proof. The report correctly retains application-selected still-needed handles rather than prescribing an all-forever retention rule.
- Current::root is canonical_root; ops_root delegates to Any root, and bounds delegates to Any bounds. The bounds' commitment roots are ops roots, not a replacement for the canonical Current root or the unresolved application execution-result root scheme. Native Current validate_batch delegates Any applicability; it does not authenticate the full application execution statement.
- Any public validate_batch borrows the DB and sealed batch; apply_batch consumes DB, rechecks storage applicability and returns DB plus local operation range. Applicability compares exact `(size, root)` at initial boundary or an ancestor state and verifies floors. It neither checks worker authorization nor certifies application parent/runtime/provenance. Apply appends/publishes but is explicitly not durable; commit/sync/start_sync completion is required separately. Shared context checking/writer fencing must encompass validation and use.
- Glue AnyMerkleized's private inner Arc/shared DB clone are reusable handles; Deref exposes the batch reference, not its inner Arc/refcount. Generic Merkleized gives root/new_batch and DatabaseSet sealed forks, not a public tree or unsealed-parent branching API. No new get_parent/is_ancestor/refcount/reconciliation/tree actor is called for.
- Any prune consumes DB and leaves root/snapshot unchanged; Current checks safe sync boundary and commits operation log before persisted pruning metadata. These storage limits do not establish application retention or durable output/cursor/certificate/provenance linkage. Native Stateful's context traversal and pruning helpers remain private and Application-dependent examples; Constantinople separately supplies consensus ancestry and supplied batches, then seals its staged computation. Neither becomes an unchanged native execution tree.

The proposed root addition to `docs/execution/qmdb.md` preserves exact execution-context association, still-needed handle ownership, canonical versus ops roots, shared fence and logical drop versus Storage's physical retention. It does not alter parent binding, reuse validation, own-direct versus imported signing provenance, root-before-own-sign, f+1 statement requirements or cut no-wait.

Remaining limits: source/API clarification only, no build/pruning test/worker quiescence proof/rootless fork implementation. Schemas/backend variants/sealing/retention and prune cadence remain open; no storage projection is promoted into application execution ancestry.
'''
(b/'BODY_CODEC_CROSS_REVIEW.md').write_text(body);(b/'EXECUTION_TREE_CROSS_REVIEW.md').write_text(tree)
root=b.parents[4];receipt={'checked_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'report_hashes':m['report_hashes'],'reader_delta_hashes':m['reader_delta_hashes'],'fresh_sources':len(m['sources']),'fresh_complete_trees':m['trees'],'source_manifest_sha256':hashlib.sha256((d/'source-manifest.json').read_bytes()).hexdigest(),'reviews':{x:hashlib.sha256((b/x).read_bytes()).hexdigest() for x in ['BODY_CODEC_CROSS_REVIEW.md','EXECUTION_TREE_CROSS_REVIEW.md']},'limited_root_reader_hashes':{x:hashlib.sha256((root/x).read_bytes()).hexdigest() for x in ['docs/consensus/block-body.md','docs/execution/qmdb.md']},'not_global_final_review':True}
(b/'cross-review-receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');print(counts);print(json.dumps(receipt['reviews'],indent=2));print(receipt['source_manifest_sha256'])
