from pathlib import Path
import json,urllib.request,hashlib,datetime,concurrent.futures
base=Path(__file__).parent
pins={'native':('commonwarexyz/monorepo','534af0ede48affd35b2111522527547b4cc9bf72'),'kora':('refcell/kora','446b4c7aba80e8358486ddb43a276c5bfa183102'),'constantinople':('commonwarexyz/constantinople','3b6c92e76bf582855615844a4175b8304808f6a9')}
paths={'native':['Cargo.toml','storage/src/qmdb/batch_chain.rs','storage/src/qmdb/any/batch.rs','storage/src/qmdb/any/db.rs','storage/src/qmdb/any/traits.rs','storage/src/qmdb/any/ordered/variable.rs','storage/src/qmdb/current/batch.rs','storage/src/qmdb/current/db.rs','storage/src/qmdb/current/ordered/variable.rs','glue/src/stateful/db/mod.rs','glue/src/stateful/db/any.rs','glue/src/stateful/db/current.rs'],'kora':['Cargo.toml','crates/node/executor/src/traits.rs','crates/node/executor/src/outcome.rs','crates/node/executor/src/adapter.rs','crates/storage/qmdb/src/batch.rs','crates/storage/qmdb/src/changes.rs','crates/storage/qmdb/src/store.rs','crates/storage/qmdb/src/traits.rs','crates/storage/overlay/src/overlay.rs','crates/storage/handlers/src/adapter.rs','crates/storage/handlers/src/qmdb.rs','crates/storage/traits/src/state.rs'],'constantinople':['Cargo.toml','crates/application/src/consensus/db.rs','crates/application/src/consensus/execution.rs','crates/application/src/consensus/lifecycle.rs','crates/application/src/consensus/glue.rs']}
def fetch(pair):
 label,path=pair;repo,rev=pins[label];url=f'https://raw.githubusercontent.com/{repo}/{rev}/{path}';data=urllib.request.urlopen(url,timeout=30).read();tree=json.loads((base/(label+'-tree.json')).read_text());entry=next(x for x in tree['tree'] if x['path']==path);target=base/'sources'/label/path;target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(data);blob=hashlib.sha1(b'blob '+str(len(data)).encode()+b'\0'+data).hexdigest()
 return dict(label=label,repository=repo,revision=rev,path=path,url=url,status=200,bytes=len(data),sha256=hashlib.sha256(data).hexdigest(),git_blob=blob,tree_blob=entry['sha'],matches_tree=blob==entry['sha'])
with concurrent.futures.ThreadPoolExecutor(max_workers=6) as ex: receipts=list(ex.map(fetch,[(label,p) for label,ps in paths.items() for p in ps]))
(base/'source-manifest.json').write_text(json.dumps({'retrieved_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'receipts':receipts},indent=2)+'\n')
print(len(receipts),'fresh files; all tree matches',all(r['matches_tree'] for r in receipts))
