from pathlib import Path
import json,hashlib,urllib.request,concurrent.futures,datetime,subprocess
b=Path(__file__).parent;pins={'native':('commonwarexyz/monorepo','534af0ede48affd35b2111522527547b4cc9bf72'),'tempo':('tempoxyz/tempo','61c979a524f9af5de9c540a0088c429a44741e4c'),'constantinople':('commonwarexyz/constantinople','3b6c92e76bf582855615844a4175b8304808f6a9'),'release':('commonwarexyz/monorepo','d476a2361ce6840d2b9d0aa6fb30a924429046d4')};v=subprocess.check_output(['gh','api',f'repos/commonwarexyz/monorepo/git/trees/{pins["release"][1]}?recursive=1']);t=json.loads(v);assert not t.get('truncated');(b/'release-tree.json').write_bytes(v)
paths={'native':['runtime/src/lib.rs','runtime/src/utils/handle.rs','runtime/src/utils/supervision.rs','runtime/src/utils/signal.rs','runtime/src/utils/cell.rs','runtime/src/tokio/runtime.rs','utils/src/futures.rs','utils/src/channel/reservation.rs','utils/src/channel/mod.rs','parallel/src/lib.rs','macros/src/lib.rs','consensus/src/multimmit/actors/voter/executor.rs','glue/src/stateful/actor/core/verifications.rs','glue/src/stateful/actor/processor/mod.rs'],'tempo':['crates/consensus/src/executor/actor.rs','crates/consensus/src/executor/ingress.rs','crates/consensus/src/consensus/engine.rs','crates/consensus/src/lib.rs','crates/payload/builder/src/lib.rs'],'constantinople':['crates/application/src/consensus/execution.rs','crates/application/src/consensus/db.rs','crates/application/src/consensus/glue.rs'],'release':['runtime/src/utils/handle.rs','utils/src/futures.rs']};trees={}
for tag in pins:
 t=json.loads((b/(tag+'-tree.json')).read_text());assert not t.get('truncated');trees[tag]={x['path']:x['sha'] for x in t['tree'] if x['type']=='blob'}
def fetch(x):
 tag,p=x;r,pin=pins[tag];u=f'https://raw.githubusercontent.com/{r}/{pin}/{p}';v=urllib.request.urlopen(u,timeout=45).read();f=b/'sources'/tag/p;f.parent.mkdir(parents=True,exist_ok=True);f.write_bytes(v);blob=hashlib.sha1(f'blob {len(v)}\0'.encode()+v).hexdigest();assert blob==trees[tag][p];return {'source':tag,'repo':r,'pin':pin,'path':p,'url':u,'local':str(f.resolve()),'sha256':hashlib.sha256(v).hexdigest(),'git_blob':blob,'tree_blob':trees[tag][p],'bytes':len(v)}
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as e:rows=list(e.map(fetch,[(tag,p) for tag,ps in paths.items() for p in ps]))
(b/'source-manifest.json').write_text(json.dumps({'fresh_fetched_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'pins':pins,'sources':rows},indent=2)+'\n');print(len(rows),'fresh blob-matched files /4complete trees')
