from pathlib import Path
import json,hashlib,urllib.request,concurrent.futures,datetime,subprocess
b=Path(__file__).parent;pins={'native':('commonwarexyz/monorepo','534af0ede48affd35b2111522527547b4cc9bf72'),'nunchi':('nunchi-labs/sdk','eea35ced709f68c15d6fbc8bcc754696a7e44374'),'constantinople':('commonwarexyz/constantinople','3b6c92e76bf582855615844a4175b8304808f6a9'),'reth':('paradigmxyz/reth','038edab20dfff017f7a7502e683c732e5628ad89'),'tempo':('tempoxyz/tempo','61c979a524f9af5de9c540a0088c429a44741e4c')};paths={'native':['Cargo.toml','consensus/src/lib.rs','consensus/src/multimmit/engine.rs','consensus/src/multimmit/machine/durability.rs','consensus/src/multimmit/machine/reducer.rs','consensus/src/multimmit/machine/finality.rs','consensus/src/multimmit/machine/algebra/tips.rs','consensus/src/multimmit/actors/resolver/actor.rs','consensus/src/multimmit/types/block.rs','consensus/src/multimmit/types/history.rs','utils/src/acknowledgement.rs','storage/src/archive/mod.rs'],'nunchi':['mempool/src/actor.rs','mempool/src/pool.rs','mempool/Cargo.toml','Cargo.toml'],'constantinople':['crates/mempool/src/webserver/actor.rs'],'reth':['crates/transaction-pool/src/traits.rs'],'tempo':['crates/payload/builder/src/lib.rs']}
def tree(tag):
 r,p=pins[tag];v=subprocess.check_output(['gh','api',f'repos/{r}/git/trees/{p}?recursive=1']);t=json.loads(v);assert not t.get('truncated');(b/(tag+'-tree.json')).write_bytes(v);return tag,{x['path']:x['sha'] for x in t['tree'] if x['type']=='blob'}
with concurrent.futures.ThreadPoolExecutor(max_workers=5) as e:trees=dict(e.map(tree,pins))
def fetch(x):
 tag,p=x;r,pin=pins[tag];u=f'https://raw.githubusercontent.com/{r}/{pin}/{p}';v=urllib.request.urlopen(u,timeout=45).read();f=b/'sources'/tag/p;f.parent.mkdir(parents=True,exist_ok=True);f.write_bytes(v);blob=hashlib.sha1(f'blob {len(v)}\0'.encode()+v).hexdigest();assert blob==trees[tag][p];return {'source':tag,'repo':r,'pin':pin,'path':p,'url':u,'local':str(f.resolve()),'sha256':hashlib.sha256(v).hexdigest(),'git_blob':blob,'tree_blob':trees[tag][p],'bytes':len(v)}
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as e:rows=list(e.map(fetch,[(tag,p) for tag,ps in paths.items() for p in ps]))
(b/'source-manifest.json').write_text(json.dumps({'fresh_fetched_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'pins':pins,'complete_trees':5,'sources':rows},indent=2)+'\n');print(len(rows),'fresh blob matched files')
