from pathlib import Path
import hashlib,json,subprocess,datetime
root=Path.cwd();out=root/'assets/review/commonware-reuse-20261004/wave13/body-seams';sha=lambda b:hashlib.sha256(b).hexdigest();record={'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline':'78d5f2eca347b0fc04b7f7d31ff858cc2a69bee4','fresh_downloads':0,'scope':'Independent reread/rehashed source and proposed contract fit, no compilation or runtime proof','reports':[]}
for p in ['pool-orderer-seams/REPORT.md','pool-orderer-seams/READER_DELTA.md','execution-seams/REPORT.md','execution-seams/READER_DELTA.md']:
 path=root/'assets/review/commonware-reuse-20261004/wave13'/p;record['reports'].append({'path':str(path.relative_to(root)),'sha256':sha(path.read_bytes())})
pool=json.loads((root/'assets/review/commonware-reuse-20261004/wave13/pool-orderer-seams/seam-receipt.json').read_text());execution=json.loads((root/'assets/review/commonware-reuse-20261004/wave13/execution-seams/EVIDENCE.json').read_text());record['page_checks']=[]
checks=pool['reviewed_pages'];
for e in execution['pages']:checks[e['path']]=e['sha256']
for p,d in checks.items():b=(root/p).read_bytes();assert sha(b)==d;assert b==subprocess.check_output(['git','show',record['baseline']+':'+p]);record['page_checks'].append({'path':p,'sha256':d,'baseline_equal':True})
record['source_checks']=[]
for folder,treefolder,p in [('wave10/body-coherence/independent-cross-review/sources/nunchi','wave10/body-coherence/independent-cross-review/trees/nunchi.json','mempool/src/actor.rs'),('wave10/body-coherence/independent-cross-review/sources/nunchi','wave10/body-coherence/independent-cross-review/trees/nunchi.json','mempool/src/pool.rs'),('wave11/execution-coverage/sources','wave11/body-coverage/trees/native.json','glue/src/stateful/db/mod.rs'),('wave11/execution-coverage/sources','wave11/body-coverage/trees/native.json','storage/src/qmdb/sync/engine.rs')]:
 src=root/'assets/review/commonware-reuse-20261004'/folder/p;treepath=root/'assets/review/commonware-reuse-20261004'/treefolder;tree=json.loads(treepath.read_text());assert not tree['truncated'];idx={e['path']:e['sha'] for e in tree['tree']};b=src.read_bytes();blob=hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest();assert idx[p]==blob;record['source_checks'].append({'path':p,'retained_source':str(src.relative_to(root)),'sha256':sha(b),'git_blob':blob,'tree':str(treepath.relative_to(root)),'tree_sha256':sha(treepath.read_bytes()),'scope':'Retained independently pinned primary bytes/complete tree, reread/rehashed not fresh retrieval'})
(out/'CROSS_REVIEW_RECEIPT.json').write_text(json.dumps(record,indent=2)+'\n');print(json.dumps({'reports':record['reports'],'pages':len(checks),'source_checks':len(record['source_checks']),'receipt_sha':sha((out/'CROSS_REVIEW_RECEIPT.json').read_bytes())},indent=2))
